# Generated by Django 5.2.8 on 2025-12-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', storage='coolweb.storage.CloudinaryDirectStorage', upload_to='profile_pics'),
        ),
    ]
