# Generated by Django 5.2.8 on 2025-12-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
    ]
